### ISSUE TITLE
plusieurs administrateurs du projet  www.refuges.info

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#1]
Sur github, il y a un truc qui s'appel "organisation" qui permet d'être plusieurs admin du projet et sortir ainsi de mon compte perso. 
genre si vous voulez changer je ne sais quel paramètre, ajouter un autre développeur et avoir moins la sensation que c'est "à moi"

Moi, perso, je m'en fou si ça reste comme ça, mais si vous préférez, j'ai découvert un bouton qui s'appel "transférer ce projet à un autre compte ou une organisation"

**Comment by LeOSW42** [comment]
Après réflexion, moi je ne suis pas contre le transférer à une organisation, sur laquelle on peut mettre plusieurs projets (Apps mobiles dans mon cas)

**Comment by sletuffe** [comment]
pas de problème pour moi, je te laisse créer l'organisation wri ou refuges.info, me passer moi, dominique et toi comme admin de cette orga, y passer ton appli mobile et me donner le nom de l'organisation.
Je transférerais le projet www.refuges.info là bas.

Il faudra penser à mettre à jour nos logiciels utilisant git vers la nouvelle adresse

**Comment by LeOSW42** [comment]
Créé là : @RefugesInfo

Je vous ai invité tous les 3, une fois accepté, je vous pase en owners et vous pouvez tout y faire.
Voilà tout

Léo

**Comment by LeOSW42** [comment]
Merci, je pense que tout au même endroit m'aidera à m'y retrouver

**Comment by Dominique92** [comment]
J'ai accepté

**Comment by sletuffe** [comment]
j'ai oublié de le préciser mais vous avez dû le voir, j'ai fais le transfert. Bizarrement, l'ancienne adresse du repo répond toujours, de sorte, que même sans rien changer, ça continue de marcher.
