### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by LeOSW42** [RefugesInfo/www.refuges.info#10]
Se pencher sur la question du cache, pour mettre en cache :
- La carte
- Des fiches
- L'inventaire d'un massif

**Comment by sletuffe** [comment]
le nettoyeur à encore frappé, si quelqu'un compte s'y mettre, qu'il ré-ouvre

**Comment by Dominique92** [comment]
Ho purée, non ! pas de caches SVP.
Je passe ma vie à les contourner (dev, mise à jour, ...)
Pas vu cuilà sans ça, je l'aurais barré de rouge !

**Comment by sletuffe** [comment]
hahaha ;-) et pourtant, c'est bien dans un cas comme ça que le cache est indispensable, puisque, il me semble, son objectif était de pouvoir "visiter refuges.info sur mobile, même hors réseau" alors, forcément, sans cache, c'est plus compliqué !

Mais pas de panique, léo a dit qu'il n'avait plus le temps de s'occuper de l'appli mobile

**Comment by Dominique92** [comment]
Ha, le cache appli.
Ok, j'en ai un dans la web app, évidement...
