### ISSUE TITLE
carte IGN sur mobile

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#12]
IGN et leaflet, y'a-t-il un espoir ?

solution par là : https://gist.github.com/al3xandre/8331447 ?

**Comment by Dominique92** [comment]
C'est clos, il me semble.

**Comment by sletuffe** [comment]
Je crois qu'il est question de :
http://www.refuges.info/mobile/#map
Et on a toujours pas de carte IGN

**Comment by Dominique92** [comment]
Oups
