### ISSUE TITLE
Passage du dossier /exportation au MVC

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#26]
Tout dans le titre, à voir toutefois à coupler avec ça : http://www.refuges.info/forum/viewtopic.php?t=5259

**Comment by LeOSW42** [comment]
J'ai passé le formulaire d'exportation pour utilise l'API, je vous laisse nettoyer, moi je ne vois plus rien qui utilise l'exportation.

**Comment by sletuffe** [comment]
ben aller, y'a plus qu'a le virer cui'là, c'est le ménage !
Je dégage
