### ISSUE TITLE
L'export en GPI ne fonctionne pas

### ISSUE THREAD

**Issue by LeOSW42** [RefugesInfo/www.refuges.info#30]
L'export en GPI sur l'API ne fonctionne pas

**Comment by sletuffe** [comment]
GPI = Garmin Point of Interest
C'est un format compatible avec la totalité des GPS du constructeur garmin, qui permet le rangement en catégories, avec icones, alti, nom, description et autres options dont j'ai oublié la liste.

D'après les stats du site, c'est utilisé à hauteur de environ 15 appels par mois.
A titre personnel, je m'en sers toujours, mais je ne fais un export que tous les 6 mois seulement.

Coté technique, c'est généré de la manière suivante :
Je génère un gpx que je passe à l'utilitaire gpsbabel, lui me sort un gpi

**Comment by sletuffe** [comment]
bon, ça ne marche toujours pas et l'ancien code a été désactivé. Je propose de clore ce bug vu que personne ne s'en sert, j'ai posé sur le forum de wri une question non plus de dév, mais de savoir si certain l'utilise encore. Si la réponse est non on cloturera tout ça et on en parlera plus
