### ISSUE TITLE
Export commentaires impossible

### ISSUE THREAD

**Issue by LeOSW42** [RefugesInfo/www.refuges.info#31]
L'export de commentaires pour des cabanes ne se trouvant pas dans un massif de type 1 (un massif normal quoi) n'est pas possible.

Dans le modèle commentaires, on ne prend que les commentaires d'un point massif de type 1 (sinon on a un problème de duplication dans la réponse)

**Comment by sletuffe** [comment]
les commentaires n'étant plus exportés du tout, on peut fermer.
A voir à l'avenir si on fait un appel pour fournir les commentaires sur un appel type /api/commentaires
