### ISSUE TITLE
Export contenu message forum

### ISSUE THREAD

**Issue by LeOSW42** [RefugesInfo/www.refuges.info#34]
Il serait sympa d'exporter le contenu du message posté sur le forum dans l'API/contributions.
On pourrait alors le mettre dans le flux RSS

**Comment by sletuffe** [comment]
J'ai l'impression que RSS perd de plus en plus d'adepte ? et que sur wri je ne sais même plus moi même où trouver le flux ! (heu, il existe encore ?)
