### ISSUE TITLE
api : paramètre vide plutôt que mot clé pour sélectionner "tout"

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#41]
Pour être encore plus concis, pourrait-on avoir :
à la place de :
api/bbox?bbox=world&type_points=all&nb_points=2
avoir :
api/bbox?nb_points=2

De manière général, il me semble plus facile de retenir que l'absence ne sera pas un "ET" sur les conditions que se rappeler quel est le mot clé.

Cette suggestion pourrait s'appliquer donc pour :
bbox=world
type_points=all
nb_points=all

if (!isset($_REQUEST['bbox']))
  equivalent à bbox="world"

**Comment by Dominique92** [comment]
C'était ma première réaction mais je pense que Léo a été sage en ne mettant pas tous ces paramètres par défaut car une url sans paramètres générerait la réponse de la mort.

**Comment by sletuffe** [comment]
de la mort ?
broaf, au pire ça fait 3000 points in the wild, pas de quoi tuer un navigateur non ?
Sans compter que y'en a bien un qui passera nb_points=all à un moment et qu'il faut bien que le serveur y survive.

La simplification pour tout ce qui n'ont pas la doc sous les yeux sera gagnée sur la fois ou quelqu'un se trompera il me semble.

**Comment by sletuffe** [comment]
bon, ça n'avait pas l'air de motivé les troupes, on ferme
