### ISSUE TITLE
Ajout paramètre API : Expires

### ISSUE THREAD

**Issue by Dominique92** [RefugesInfo/www.refuges.info#46]
Quoi: obtenir des extractions avec des durées de validité différentes du défaut 60 secondes
Comment: Ajouter un paramètre expires=1234 (valeur par défaut 60)
Pourquoi: dans au moins un cas, j'en aurais eu besoin pour afficher le nouveau réseau de massifs utilisé en fond de l'éditeur quand on vient de sauvegarder une évolution.
J'ai actuellement utilisé le contournement consistant à ajouter ?<?=time()?> à l'appel de l'API, mais ce n'est pas très beau. J'aurais préféré &expires=0
https://github.com/sletuffe/www.refuges.info/blob/master/vues/nav.js#L46

**Comment by sletuffe** [comment]
Je dirais que ça n'est pas au serveur de modifier son information concernant le cache mais au client de ne pas obéir la recommandation de cache du serveur !
En plus, là ça fait vraiment tordu, puisque ça serait le client qui demande au serveur de ne pas lui recommander de suivre son conseil !
Client : "Dites moi serveur, pourriez me recommander de ne pas vous écouter ?"

Non, en effet, j'ignore si la class de leaflet sait forcer le navigateur à refaire la requête (cache:false ?) mais je trouve ton contournement, à défaut d'être beau, moins moche que ta suggestion.

Tiens, Jquery supporte cette fonction :
http://api.jquery.com/jquery.ajax/

hahahahahaha :
If set to false, it will force requested pages not to be cached by the browser. Note: Setting cache to false will only work correctly with HEAD and GET requests. It works by appending "_={timestamp}" to the GET parameters
