### ISSUE TITLE
BUG /api/polygones type_geom = polylines

### ISSUE THREAD

**Issue by Dominique92** [RefugesInfo/www.refuges.info#47]
/api/polygones avec type_geom = polylines rend un code Json invalide sur des polylines multiples:

"geometry": {"type":"MultiLineString","coordinates":[[[5.5766,43.83295],[5.5766,43.83295]]],[[[5.1501,43.77248],[5.45123,43.87011]]]},

Il ne faudrait pas dépiler toutes les [] entre les morceaux de lignes:

"geometry": {"type":"MultiLineString","coordinates":[[[5.5766,43.83295],[5.5766,43.83295]],[[5.1501,43.77248],[5.45123,43.87011]]]},

**Comment by LeOSW42** [comment]
Est-ce que tu as un exemple de ça pour moi ? Je ne vois pas où est-ce que c'est utilisé.

**Comment by Dominique92** [comment]
En effet, j'aurais pu donner un exemple: http://www.refuges.info/api/polygones?type_polygon=12&type_geom=polylines&bbox=8.854,47.85,8.86168,47.8527
Il correspond au polygone multiple: http://www.refuges.info/nav/3116

J'ai noté ce bug en passant un jour dessus mais il n'y a aucune urgence ni priorité car personne à ma connaissance ne l'utilise
