### ISSUE TITLE
brange master pas totalement fonctionnelle

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#50]
J'ai pas totalement analysé mais dans ce commit : https://github.com/RefugesInfo/www.refuges.info/commit/4473e0c7d8f90f3c836d80d290cc75fc7931f4f5

que j'ai fais et qui "merge" avec certain des votre, j'ai/nous avons introduit un bug, voir http://sly.refuges.info/nav/4/massif/Vercors/

j'ai rien tenté, j'ai pas creusé, j'ai juste remis la prod dans l'état d'avant ce commit, donc ne pas faire de "git pull" en prod pour l'instant

**Comment by Dominique92** [comment]
Voilà. En ajoutant le paramètre BBOX à la carte NAV, ça marche.
Reste un bug que je vais suivre sur une autre issue: l'API massif commet une erreur SQL quand le paramètre BBOX n'est pas donné.
