### ISSUE TITLE
L'API massif commet une erreur SQL quand le paramètre BBOX n'est pas donné.

### ISSUE THREAD

**Issue by Dominique92** [RefugesInfo/www.refuges.info#51]
http://www.refuges.info/api/massif?type_points=all&massif=4
Non bloquant puisque j'ai mis la carte NAV en BBOX
Je laisse les spécialistes de PostGres mettre ça au point

  SELECT points.*,
         points_gps.*,
         type_precision_gps.*,
         point_type.*,COALESCE(phpbb_users.username,nom_createur) as nom_createur,
         ST_X(points_gps.geom) as longitude,ST_Y(points_gps.geom) as latitude,
         extract('epoch' from date_derniere_modification) as date_modif_timestamp,
     extract('epoch' from date_creation) as date_creation_timestamp
         
         ,polygones.site_web,polygones.url_exterieure,polygones.message_information_polygone,polygones.source,polygones.nom_polygone,polygones.article_partitif,polygones.id_polygone_type,polygones.id_polygone
         
         FROM points NATURAL JOIN points_gps NATURAL JOIN type_precision_gps NATURAL JOIN point_type LEFT join phpbb_users on points.id_createur = phpbb_users.user_id INNER JOIN polygones ON ( ST_Within(points_gps.geom,polygones.geom) AND polygones.id_polygone IN (4)   ) 
  WHERE
     1=1
    
 AND ST_Within(points_gps.geom,ST_SetSRID(ST_MakeBox2D(ST_Point(, ), ST_Point( ,)),4326)) 
 AND points_gps.id_type_precision_gps != 5
 AND modele!=1
  
ORDER BY point_type.importance DESC
  
LIMIT 250
  
    Erreur PDO : array (
  0 => '42601',
  1 => 7,
  2 => 'ERREUR:  erreur de syntaxe sur ou près de « , »
LINE 16: ...(points_gps.geom,ST_SetSRID(ST_MakeBox2D(ST_Point(, ), ST_Po...
                                                              ^',
)

**Comment by LeOSW42** [comment]
Je crois que ça a été fixé avec le commit dc4f7682acd6a0978c5a7edd61dd187b4e82568b
