### ISSUE TITLE
url d'accès à la fiche d'un point depuis l'export geojson

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#55]
Actuellement, l'export geojson de l'api ne fourni par l'url (pour navigateur) d'accès à la fiche d'info du point. De sorte qu'un service externe qui appellerait notre api est responsable, s'il en a besoin, de créer un lien de retour vers : http://www.refuges.info/point/$id

Si d'aventure nous changeons nos format d'url (genre  http://www.refuges.info/refuge/$id) tout le monde devra mettre à jour son code. Pour réduire ce besoin, je suggère d'expedier dans le geojson l'url vers laquelle pointer un navigateur pour obtenir la fiche de wri.
C'est pas énormément d'octets en plus mais ça évitera le cas, certes peu probable cité ci-avant.

Et notre propre leaflet pourra aussi l'utiliser pour avoir de jolies url ( http://www.refuges.info/point/1114/sommet/Diablerets-Grimsel/Pointe-de-la-Plaine-Morte/) sans trop d'efforts

Code déjà commité, si vous pensez que c'est foireux, y'a qu'a l'annuler :
https://github.com/RefugesInfo/www.refuges.info/commit/71974dc66e7e082378dfbe2943f50369fb4855db

**Comment by Dominique92** [comment]
ça me parait plus logique

**Comment by Dominique92** [comment]
Mais il faudrait faire de même pour l'icône ?

**Comment by sletuffe** [comment]
Bonne question. 
Mais ça ne me choque pas de ne pas donner l'url de l'icône, on pourrait argumenter que le choix iconographique est à l'initiative du service appelant qui peut être différent de notre choix d'icônes. On fourni les données, l'appelant fait sa tambouille pour choisir une icône, qu'il peut au préalable copier de chez nous s'il veut.

Je continue à penser que notre choix qui est de générer un nom d'icône coté serveur n'est pas la plus pertinente mais devrait être faite coté client, tant pour notre leaflet que pour celui d'un autre ou que n'importe quel logiciel qu'il aura choisi. 
Mais tout se discute ;-)

**Comment by LeOSW42** [comment]
Bonjour à vous,

Donner le lien direct n'est pas une mauvaise chose après réflexion.
Pour l'icône, j'ai préféré donner le nom générique pour ensuite inciter le réutilisateur à utiliser son propre jeu adapté à l'utilisation. Mais ça fait plaisir de voir que vous vous appropriez ce petit bout de code et je vous laisse décider ce que vous préferez.

Léo

**Comment by sletuffe** [comment]
ok alors, pas d'url vers les icônes
