### ISSUE TITLE
L'export de point fonctionne bizzarement

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#56]
Si je demande ça :
http://sly.refuges.info/api/bbox?type_points=6&bbox=-9.4,41,23.4,48.19
ça marche car ça ne me renvoi bien que les cabanes gardées
Mais si je demande ça :
http://sly.refuges.info/api/bbox?type_points=28&bbox=-9.4,41,23.4,48.19
(les bâtiments à explorer)
ou ça :
http://sly.refuges.info/api/bbox?type_points=500&bbox=-9.4,41,23.4,48.19
(l'id du type inexistant)
ça me renvoi tout

En regardant le code, je crois comprendre qu'il y a une liste en dure : https://github.com/RefugesInfo/www.refuges.info/blob/master/controlleurs/api.points.controleur.php#L51 qui bloque.

C'est pas super pratique si on doit changer le code quand on rajoute un type !

A vu de nez j'aurais tendance à dégager ce bout de code, mais j'ai pas tout lu donc je préfère m'abstenir avant de faire une bêtise ?

**Comment by Dominique92** [comment]
Pas d'idée. J'ai toujours été paumé par ce bout du code :)

**Comment by LeOSW42** [comment]
Salut,

Pour ce bout de code, c'est en gros un moyen de traduire un mot en un id.
Mes arguments : les id sont à mes yeux évolutifs, ils peuvent changer, évoluer... mais dans l'idéal il ne faut pas changer l'interface de l'API, donc si un id change, il suffit de modifier la ligne donnée par sylvain. L'utilisateur de l'API (chemineur, la version mobile, leaflet, le mec de l'appli iPhone...) n'ont pas changer quoi que ce soit.

Moi (évidement) je trouve ça normal comme c'est.

**Comment by sletuffe** [comment]
Si vraiment on voulait traduire un "mot en id" on a la base de données pour ça "cabane non gardée" -> id = 6, pas besoin de garder en plus à coté un "cabane_non_gard" -> id = 6
Ou alors, je peine à comprendre la finalité.

Pour l'API, on voit des appels de type "http://sly.refuges.info/api/bbox?type_points=6" et le 6 c'est bien un id, donc si ça change dans notre base, les appels api fait par les autres qui ont 6 en dur seront eux aussi à changer de toute façon.
Si vraiment on voulait devenir indépendant de l'id que l'on suppose pouvoir changer, il faudrait créer un appel à l'api qui liste les types possibles. Et de là, chaque interface d'interrogation fournirait une liste avec des noms en français du type.
Je vais regarder ça si je peux simplifier un peu et proposer un patch

**Comment by sletuffe** [comment]
Ha si, ça y est, je comprends un peu mieux le but, c'est marqué dans la doc : "Les types de point à exporter, parmis la liste suivante : cabane, refuge, gite, pt_eau, sommet, pt_passage, bivouac et lac"
En apparence on maintient une liste de mot plutôt qu'une liste de nombre, mais là, comme on le voit, si j'ajoute un type je dois mettre à jour la doc et l'array de l'api et si en interne on décide de changer le nom de l'un d'entre eux on va s'ambrouiller.

Je comprends la finalité, mais je ne suis pas convaincu qu'on se simplifie la tâche. Ça va qu'on ajoute pas de nouveaux types tous les jours. La version propre mais pénible serait comme je disais de fournir un appel qui rend la liste des types possibles avec leurs id.
Bon, flemme, je crois que je vais botter en touche à ajouter mon type à la liste.. Ou au moins cours-circuiter la vérifiation "être dans la liste" pour que notre usage de l'api, même si non documenté, soit plus simple à gérer sans devoir tenir à jour plusieurs listes

**Comment by Dominique92** [comment]
Perso, je trouve plus logique de mettre un nom signifiant ex: "cabane" plutôt qu'un id ex: "7".
De toute façon, il va bien falloir aller voir quelque part à quoi correspond ce 7 alors qu'un mnémonique à l'avantage d'être compréhensible.
Quant à l'idée que le service utilisateur n'aura rien à changer ... ne vous faites pas de bile, à chaque fois que quelque chose à changé dans WRI dans le passé, l'import chemineur à explosé et j'ai dû recoder (un peu !). C'est pareil pour les autres imports des autres sites, c'est normal et je ne vois pas comment éviter ça.

**Comment by sletuffe** [comment]
C'est quand un humain écrit la requête manuellement que c'est valable. Sinon, quand c'est un logiciel qui génère la requête, autant présenter carrément le nom final qui est "cabane non gardée".
Bon, si tout le monde voit l'intérêt d'un "mot court" (et sans espace ni accent je suppose, sinon leo n'aurait pas inventé de nouveau mot mais aurait repris le nom humain) pour appeler le type par l'api, au moins, stockons ça dans la base de données.

**Comment by LeOSW42** [comment]
J'ai l'impression que vous avez compris ce que je pensais en écrivant ça.

L'API accepte aussi volontairement les id directement en chiffre, et je pense pas que ce soit nécessaire d'y ajouter batiment à explorer dedans. En fait je pense que la liste qui est proposée pour le moment est sufissante, si il veut un type évolué (comme celui que tu viens de rajouter Sylvain), bein il faut connaitre l'ID et le mettre.

Léo

**Comment by sletuffe** [comment]
Bon, j'ai mis une ligne avec FIXME et j'ai très simplement ajouté mon id à l'array.

**Comment by sletuffe** [comment]
leo> L'API accepte aussi volontairement les id directement en chiffre, et je pense pas que ce soit 
leo> nécessaire d'y ajouter bâtiment à explorer dedans.

Ben, si je ne mets pas "28" dans l'array, alors à cette ligne : https://github.com/RefugesInfo/www.refuges.info/blob/master/controlleurs/api.points.controleur.php#L162 "all" sera forcé.

Et si je n'ajoute pas "batiment_a_explorer" dans https://github.com/RefugesInfo/www.refuges.info/blob/master/controlleurs/api.points.controleur.php#L56 alors au prochain type que quelqu'un va ajouter, tout va se décaller et ce code : https://github.com/RefugesInfo/www.refuges.info/blob/master/controlleurs/api.points.controleur.php#L222 va nous remplacer le mot clé par le mauvais id vu que ça sera décalé

**Comment by LeOSW42** [comment]
En effet on pourrait envisager de laisser les ID pour ne pas repasser en all.

Je suis désolé, je ne me suis pas replongé là dedans.

**Comment by sletuffe** [comment]
oui, c'est ce que j'hésite à faire, plutôt qu'un fall back sur "all" laisser les ids tels qu'ils sont fourni et ne faire le remplacement que des "mnémonique"
Bon, je laisse de coté pour l'instant, je vois pas mal de code de vérif qui redonde avec ce que fait le modèle, je garde ça pour une week end pluvieux
