### ISSUE TITLE
Standardisation des noms de propriétés geoJson

### ISSUE THREAD

**Issue by Dominique92** [RefugesInfo/www.refuges.info#57]
Je vous propose d'utiliser, quand c'est possible, des noms de propriétés les plus répandus possibles.
Je n'ai pas trouvé de telles définitions dans http://geojson.org/geojson-spec.html mais je propose de suivre Mapbox sur les properties title, icon, fillColor, url au lieu de nom, -rien-, couleur, lien
https://www.mapbox.com/mapbox.js/example/v1.0.0/custom-marker/
https://www.mapbox.com/mapbox.js/example/v1.0.0/geojson-marker-style/
https://www.mapbox.com/mapbox.js/example/v1.0.0/markers-as-links/
(on peut assumer que iconAnchor et popupAnchor sont par défaut 1/2 de iconSize)

On peut au choix remplacer les propriétés existantes ou les livrer en double français + anglais (ce sera probablement le cas pendant une période transitoire tant que je n'aurai pas réinterfacé chemineur par exemple)
Je persiste à penser qu'il faut, en plus de la proprièté "icone" simplifiée, fournir un url d'icône car il n'est pas évident, venant de l'extérieur, de retrouver en lisant la doc API l'url des icônes d'autant qu'on peut les changer ou ajouter en interne sans préavis. Libre au service utilisateur de customiser s'il veut.

Le but n'est pas simplement de me faire plaisir: il me permet de standardiser mon plugin https://github.com/Dominique92/Leaflet.GeoJSON.Ajax qui commence à être connu y compris hors de France.
Sinon, je serai obligé de faire une traduction dans les vues/.js avant d'appeler la nouvelle version de mon plugin.

Exemple de sources dans Mapbox:
```javascript
{
    "type": "Feature",
    ...
    "properties": {
        "title": "Small astronaut",
        "icon": {
            "iconUrl": "/mapbox.js/assets/images/astronaut1.png",
            "iconSize": [50, 50], // size of the icon
            "iconAnchor": [25, 25], // point of the icon which will correspond to marker's location
            "popupAnchor": [0, -25], // point from which the popup should open relative to the iconAnchor
            "className": "dot"
        }
	}
}
{
  "type": "FeatureCollection",
  ...
    "properties": {
      "fillColor": "#eeffee"
    }
 }
{
  "type": "FeatureCollection",
  ...
    "properties": {
		title: 'Baltimore, MD',
		url: 'http://en.wikipedia.org/wiki/Baltimore'
	}
}```

**Comment by sletuffe** [comment]
Je n'ai rien contre le changement des nom de propriétés bien qu'on ne trouvera jamais de standard sur l'échange de données non standard donc c'est un peu utopique.
Mais quand je vois les propriétés "iconUrl" "iconsize" je commence à croire qu'on a pas tous la même idée en tête du rôle de cette API !
L'API dont dominique parle c'est une API dédiée à de l'affichage, celle que leo (moins l'icône) a codé, c'est une API d'échange de données. Dans de l'échange de données, icônes, couleurs, marqueurs, ancre n'ont rien à faire là selon moi.
C'est un peu comme le HTML et le css (Tiens, d'ailleurs, chez MapBox ils ont abandonné la séparation data/style ? trop chiant ;-) ? )

Bref, ça revient un peu à l'idée contenu dans le vieux code que j'ai nettoyé hier, "API interne (affichage, openlayers, leaflet)" contre "API d'export (tableur, terminaux gps)"
Je n'ai rien contre que l'on fasse les deux, mais il me semble qu'il faut que ça soit deux appels séparés.
En clair, un format geojson comme il existe et un "geojsonleaflet" qui va ajouter une url d'icône, une ancre, une couleur de fond, une police de caractère et une tout se que vous voulez qui soit d'ordre de la présentation.
Evidement, ces deux appels peuvent partager 90% du code

Tout ça n'étant qu'une idée, je ne suis ni celui qui dév l'API, ni celui qui dèv la carte !

**Comment by Dominique92** [comment]
Suivant le principe "Code déjà comité, si vous pensez que c'est foireux, y'a qu'a l'annuler", j'ai implémenté les noms de propriété title, url, fillColor.
Je met en attente icon car de codage un peu plus délicat (il y a une structure) et en discussion.

**Comment by Dominique92** [comment]
Je ferme suite à un retour arrière.
De toute façon il y a toujours du travail à la réception d'une réponse ajax. J'ai implémenté un principe de callback paramétrable dans une application donnée.
https://github.com/RefugesInfo/www.refuges.info/blob/master/vues/includes/cartes.js#L43-L52
