### ISSUE TITLE
/API/BOX paramètre type_points vide

### ISSUE THREAD

**Issue by Dominique92** [RefugesInfo/www.refuges.info#58]
Il serait utile de pouvoir définir un paramètre type_points vide à l' /API/BOX.
ça peut sembler bizarre, mais ça permet de vider complètement la carte de tout picto (pour simplement regarder la carte par exemple) sans ajouter de code.
Idéalement, le paramètre serait vide:  /API/BOX?type_points=
Il ne retournerait ... rien :)

**Comment by LeOSW42** [comment]
Ce n'est pas possible pour toi de demander un bbox en plein milieu de 
l'atlantique ? Ça me semble plus logique.
Sinon je comprends oui, je pense que c'est pas une mauvaise idée.

À noter, ça implique de corriger le formulaire d'exportation, l'API, le 
site mobile (pour ce que moi j'ai codé), plus vos trucs.

Le 09/02/2016 18:23, Dominique Cavailhez a écrit :
>
> Il serait utile de pouvoir définir un paramètre type_points vide à l' 
> /API/BOX.
> ça peut sembler bizarre, mais ça permet de vider complètement la carte 
> de tout picto sans ajouter de code.
> Idéalement, le paramètre serait vide: /API/BOX?type_points=
> Il ne retournerait ... rien :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/RefugesInfo/www.refuges.info/issues/58>.
>

-- 
LSTRONIC logo

Léo SERRE

mail leo@lstronic.com <mailto:leo@lstronic.com>
website lstronic.com <http://lstronic.com>

**Comment by Dominique92** [comment]
je peux tout faire, y compris désactiver la couche. Mais le fait de le faire avec type_points= m'évite du code bidouille et a une certaine logique vu de l'API
Actuellement, ?type_points= rend tous les points. c'est à la limite du bug

**Comment by sletuffe** [comment]
La doc dit "Les types de point à exporter, parmis la liste suivante : cabane, refuge, gite, pt_eau, sommet, pt_passage, bivouac et lac ou leur équivament numérique: 7, 10, 9, 23, 6, 3, 19, 16. La valeur all sélectionne tous les types."
"?type_points="  est donc invalide au sens de la doc, on peut donc imaginer que pour éviter de la considérer comme bug, l'api devrait retourner une erreur.

Sinon, de savoir si on devrait autoriser cette syntaxe, je comprend bien que coté Leaflet ça puisse gagner du code, mais "?type_points=" ça fait quand même bug dans le code qui appel.

Et en terme de code, ça en fera soit en plus dans l'api en php, soit en js coté leaflet, alors au final, ce qu'on tente d'économiser là on le perd ici.

**Comment by Dominique92** [comment]
Du reste, il manque 28 bâtiment en montagne :)

**Comment by sletuffe** [comment]
a priori plus de raison d'être
