### ISSUE TITLE
L'exportation retourne moins de choses qu'avant

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#59]
L'API en mode gpx est plus radine que la version d'avant. Avant on pouvait avoir un export quasi complet des points (remarques, accès, nb de place) 
Le code était : https://github.com/RefugesInfo/www.refuges.info/blob/755379e93889519865986d87b0d4a88598b9e5d5/modeles/exportation.php#L435

Pourtant le code à l'air d'exister : https://github.com/RefugesInfo/www.refuges.info/blob/master/vues/api/points.vue.gpx#L35
Mais le mode "complet" n'a  pas l'air activable

**Comment by LeOSW42** [comment]
Normalement il faut demander ?detail=complet.

En effet faudrait ajouter ça dans le formulaire d'exportation par défaut.

Le 09/02/2016 18:36, sly - sylvain letuffe a écrit :
>
> L'API en mode gpx est plus radine que la version d'avant. Avant on 
> pouvait avoir un export quasi complet des points (remarques, accès, nb 
> de place)
> Le code était : 
> https://github.com/RefugesInfo/www.refuges.info/blob/755379e93889519865986d87b0d4a88598b9e5d5/modeles/exportation.php#L435
>
> Pourtant le code à l'air d'exister : 
> https://github.com/RefugesInfo/www.refuges.info/blob/master/vues/api/points.vue.gpx#L35
> Mais le mode "complet" n'a pas l'air activable
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/RefugesInfo/www.refuges.info/issues/59>.
>

-- 
LSTRONIC logo

Léo SERRE

mail leo@lstronic.com <mailto:leo@lstronic.com>
website lstronic.com <http://lstronic.com>

**Comment by sletuffe** [comment]
Corrigé ici : 
https://github.com/RefugesInfo/www.refuges.info/commit/c1a07f28a7da6dce9e08ef960e3ec9fd3ebffba8
