### ISSUE TITLE
Points externes en provenance de l'Overpass API : url

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#60]
yo,

Serait-il possible dans le nouveau code qui appel l'overpass api de faire le changement permettant d'utiliser l'url overpass indiquée dans la config :
https://github.com/RefugesInfo/www.refuges.info/blob/master/includes/config.php#L136

Je souhaite faire quelques tests de performances et j'aurais moins de mal en pouvant définir mon url d'appel.
Avec comme avantage une bascule plus aisée dans le cas où ça planterait

**Comment by DC92** [comment]
Ya.

C'est fait là: https://github.com/RefugesInfo/www.refuges.info/commit/8744752c49cbeab36e16d186a5ed613b6de0efe8#diff-07ca2f69e85c51dfe5cb2ed7bae50f32R83

Et pull www
