### ISSUE TITLE
parkings provenance osm

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#61]
Les requêtes overpass qui sont envoyées incluent :
node["amenity"~"parking"]

Or, l'opérateur ~ veut dire "contient" et si on a par exemple des amenity=plane_parking on va les afficher.
Bon, dans les faits ça ne doit pas exister plane_parking mais on a des risques de se retrouver avec des trucs qu'on ne voudrait pas, exemple à chambéry : les amenity=bycle_parking. "=" me semble être l'opérateur a préférer.

**Comment by Dominique92** [comment]
Fait
