### ISSUE TITLE
ne pas afficher les parkings privés

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#62]
Pour ne pas afficher les parking privés il faudrait remplacer dans la requête :
["amenity"~"parking"] par ["amenity"="parking"]["access"!="private"]

J'ai cherché dans le code, mais j'ai l'impression que quelqu'un a fait de l'excès de zèl dans la factorisation vu que je n'arrive plus à passer à la requête de mon choix :
https://github.com/RefugesInfo/www.refuges.info/blob/master/vues/point.js#L37

**Comment by Dominique92** [comment]
Ho purée... il avait salement fumé la moquette le gars !
J'arrive même pas à me relire 15 jours plus tard :(
Va falloir faire simple Mr Dom92

Au fait, je n'ai pas trouvé la syntaxe générale. As tu un lien qui va bien?
En + j’aimerais afficher les arrêts de bus (à charge de chacun de se renseigner sur les horaires, ... mais ça permet de savoir qu'un bus passe par une vallée reculée) Je n'ai pas réussi à construire une requête qui fait ça.

**Comment by Dominique92** [comment]
Voilà. J'ai simplifié et généralisé l'interface
Ici pour les points (en JS puisqu'il n'y a pas de cases à checker) https://github.com/RefugesInfo/www.refuges.info/blob/master/vues/point.js#L38-L43
Ici pour NAV : https://github.com/RefugesInfo/www.refuges.info/blob/master/vues/nav.html#L103-L127

**Comment by sletuffe** [comment]
Pour la documentation, j'utilise ça : http://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide et ça : http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#By_tag_.28has-kv.29

Oui, c'est un peu redondant, la deuxième est plus complète mais couvre encore plus de fonctionnalités
