### ISSUE TITLE
message d'erreur au cas où l'API ait un problème

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#63]
Sur le www je viens de reçevoir un popu qui m'indique "json error, truc machin, serveur pas content tout ça"
Pour moi, ça sert ! Mais pour le M. lanbda, pas top. Y'aurais moyen de restreindre uniquement quand debug=yes ?

**Comment by LeOSW42** [comment]
Pour info, c'est pas l'API WRI qui plante mais cette OSM.

Le 15/04/2016 12:19, sly - sylvain letuffe a écrit :
>
> Sur le www je viens de reçevoir un popu qui m'indique "json error, 
> truc machin, serveur pas content tout ça"
> Pour moi, ça sert ! Mais pour le M. lanbda, pas top. Y'aurais moyen de 
> restreindre uniquement quand debug=yes ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/RefugesInfo/www.refuges.info/issues/63>
>

-- 
*Léo Serre*
LSTRONIC

**Comment by sletuffe** [comment]
J'ai oublié de préciser, mais oui, c'est quand l'overpass distante a un problème

**Comment by Dominique92** [comment]
ça vient de mon mécanisme AJAX : mon debug par alert est un peu lourd.
Je suis passé à un debug par console.log mais j'ai laissé traîner ceux là
Je refais une intégration de ma lib actuelle et je vous relivre. Il y a aura toujours les traces sur la console: c'est moins facile à faire récupérer par qqun qui a un pb, mais moins polluant pour l'utilisateur lambda. Quand au flag debug, il n'est pas facile à récupérer dans la lib JS et il est souhaitable de pouvoir récupérer les traces quand même.
Restera à savoir pourquoi overpass bug. ça voudrait dire que ce que le serveur renvoie n'est pas Json, (le message d'erreur est généré à l'arrivée du paquet, bien avant le traitement de la couche overpass).

**Comment by sletuffe** [comment]
C'était un bug passagé, depuis plus de problèmes. Mais pour éviter de faire peur, ne simplement rien afficher ni point ni console de log, ça me semble le bon compromis.

**Comment by Dominique92** [comment]
Hum. générer des messages console sur des erreur AJAX, ça ne me gène pas.
S'il y a des pb à l'interface de WRI, on aura des erreur 404, 500 ou autre, et ça me semble intéressant de signaler à l'utilisateur qu'il y a bien un pb et de lui donner l’occasion de faire des remontées précises.
Sinon, je peux trouver un système pour virer les messages lors de la compression de la lib.

**Comment by Dominique92** [comment]
P.S. Mon interface AJAX génère des erreurs dans 3 cas:
- XMLHttpRequest non implémenté dans ce browser (je n'en connais pas aujourd'hui, mais ça peut revenir avec les mobiles)
- Code retour http autre que 200
- Erreur de syntaxe du json

**Comment by sletuffe** [comment]
Si l'erreur de syntaxe peut rester en console, très bien. Le problème d'utilisation sur les fiches c'est que si on balade la carte, on a un popu à chaque déplacement

**Comment by Dominique92** [comment]
Bon voilà. j'ai viré les console.log dans la lib compressée, ce qui répond à la demande puisque le mode debug WRI appelle les sources de Leaflet qui, elles contiennent les traces console.log
