### ISSUE TITLE
carte /nav "code html au survol" et taille réduite

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#64]
Depuis les commit du 14 avril, sur le www la carte se comporte ainsi :
![carte-www refuges info](https://cloud.githubusercontent.com/assets/732006/14761404/cbf6d99e-0960-11e6-9369-52dcd0b76042.jpeg)

**Comment by DC92** [comment]
ça c'est marrant: j'ai écrit le patch ce matin !
j'attendais de l'avoir secoué un peu car il change pas mal de chose mais, avec une bonne campagne de tests, on y va.
Moralité: ne jamais appeler une variable "title" parce qu'elle finit tôt ou tard en attribut d'un élément html ou canvas :(
