### ISSUE TITLE
export gpx non conforme xml

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#65]
Le champs <desc> du format exporté en gps laisse traîner des & qui devraient être xmlentitiesencodés : $amp;

Peut-être y'a-t-il d'autre charactères, mais je pense qu'il faudrait passer tous les champs à cet encodage.

Pour info, j'ai exporté en gpx et lancé cette commande : 
`gpsbabel -w -i gpx -f "points.gpx" -x nuketypes,tracks,routes -o garmin_poi -F "points-converted" `

qui me répond :
`GPX:Read error: Expected '#' or '[a-zA-Z]', but got ' '. (points.gpx, line 6937, col 24)`

et à cette ligne, il y a un "&"

**Comment by LeOSW42** [comment]
Je suis dessus.

**Comment by LeOSW42** [comment]
Nota; Pour le GPI, je vais adopter la même stratégie que pour le KMZ
