### ISSUE TITLE
L'API retourne une URL absolue avec un schéma fixé : http

### ISSUE THREAD

**Issue by Dominique92** [RefugesInfo/www.refuges.info#66]
Par exemple, https://www.refuges.info/api/polygones?type_polygon=1&bbox=... retourne :+1: 
... "properties": {
"lien":"http://www.refuges.info/nav/12/massif/Aiguilles-rouges/",
"couleur":"#c0302f",
...
Dans le cas du site sous HTTPS, cliquer sur un massif retourne au site en HTTP
Idem pour les icônes, ...

**Comment by Dominique92** [comment]
Je prend la modif : je vais passer toutes les références en https: qui peut le + peut le moins.
Mais est-ce la meilleure solution ? (voir pb de perf mobile en zone limite)

**Comment by sletuffe** [comment]
j'avais jamais lu ce ticket !
et choisir de renvoyer un lien sans schema :
"lien":" //www.refuges.info/nav/12/massif/Aiguilles-rouges/" ?
ou même local : 
"lien":" /nav/12/massif/Aiguilles-rouges/" ?
à compléter en js ?

**Comment by Dominique92** [comment]
choisir de renvoyer un lien sans schema :
à compléter en js ?

Ben non : le lien prend par défaut le schéma de la page sur laquelle il est, quel que soit la façon de l'appeler (html, js, XMLHttpRequest, ...)
Et ceci même si ce n'est pas le site de la page affichée (tuiles IGN dans une carte sur une page WRI, ...)
C'est pratique et logique : si je choisis d'afficher la page en http je voudrais aussi qu'il charge toutes ses dépendances comme ça.
J'ai tout écrit comme ça. Faut pas faire comme ça ?

**Comment by sletuffe** [comment]
Je suis pris en flagrant délit de ne pas avoir vérifié ! Après contrôle, ça marche impécable et comme on s'y attendrait ;-)
Sans doute mon insupportable envie de rangement s'est dit que si le ticket était toujours là, c'est que le problème n'était pas résolu.
hop, un de moins
