### ISSUE TITLE
ressources\refuges-structure.sql

### ISSUE THREAD

**Issue by Dominique92** [RefugesInfo/www.refuges.info#68]
Plutôt une question : ce fichier semble généré à partir de phpPgAdmin mais je ne sais pas trop comment.
Je découvre qu'il y a un delta avec les vraies tables de la base de prod (ex : point_type.symbole)
Quand / comment le mettre à jour ?
La question se posera d'ailleurs lors du passage en phpbb V3 : les tables et champs sont différents et il faudra ajouter points.topic_id

**Comment by LeOSW42** [comment]
Salut,
Normalement, ce fichier est généré depuis phppgadmin ou autre outil de gestion de la base où il est possible d'exporter une base SQL. Il faut alors choisir de n'exporter que la structure.
Par rapport à quand, je ne sais pas !
Léo

**Comment by Dominique92** [comment]
Merci. ça en a l'air en tout cas. Ma question porte aussi sur l'usage de ce fichier. Pour l'install d'une nouvelle base ?
Et aussi sur sa mise à jour. Aurait-on oublié de l'updater ? ou y a t'il une raison plus subtile. Je ne veux pas tout casser.

**Comment by LeOSW42** [comment]
Le fichier est utiliser pour l'install d'une nouvelle base, où il suffit d'importer la structure pour directement créer les bonnes colonnes, avec les bonnes contraintes, séquences et relations.
On a très certainement oublié de le mettre à jour, et tu peux l'écraser (GIT se souvient de tout !). Si tu n'y arrives pas, je pourrais le faire demain.

En tout cas, bravo pour ton travail, il manque un mini pied de page sur le forum et tout y est !

**Comment by Dominique92** [comment]
"En tout cas, bravo pour ton travail, il manque un mini pied de page sur le forum et tout y est !" : ça avance mais il y a encore beaucoup de subtilités à ajuster :) ... et comme j'y travaille en dernière priorité...

Pour l'instant, je visais la réincorporation des <sym> ça marchait à une époque, je ne sais pas pourquoi ça a disparu : ça ne devrait pas être bien difficile à remettre dans l'API. Je regarde ça.

Oui, pour le refuges-structure.sql ça fait un moment que je tourne autour. Je vais l'updater au prochain commit. Mais je pense que si quelqu'un veut réinstaller WRI à partir du GIT, il va lui manquer beaucoup d'info, en particulier la table point_type, les wiki, ...

**Comment by LeOSW42** [comment]
Oui, le travail de documentation serait monstre, mais déjà fournir la structure c'est très sympa !

Bonne chance pour la suite alors !

**Comment by sletuffe** [comment]
dom : généré à partir de phpPgAdmin mais je ne sais pas trop comment.
http://www.refuges.info/phppgadmin/ -> base refuges -> en haut à droite "exporter"
dom: Quand le mettre à jour ?
Dès que quelqu'un s'en sent le courage ;-)
Le dernière fois, ça s'est passé comme ça : Quelqu'un (toi ?) me demande "je peux avoir une copie de la base pour faire des tests", j'ai dû le faire et j'ai posé le fichier sur git juste par praticité et en me disant, si quelqu'un le demande avant que la table ne change, il sera là ;-)

**Comment by sletuffe** [comment]
Pour ce qui est de "réinstaller WRI" ça il manquera bien plus que le wiki, il manque toutes les données.
Par contre, avec ce fichier sql, celui qui veut se faire la main sur le logiciel de refuges.info, avoir une copie locale pour test, adapter le logiciel pour un autre usage, ça devrait (presque) être suffisant.
Dans les faits, il nous posera sans doute des questions, et c'est à ce moment qu'on lui dira oulla, le sql est trop vieux, hop, voilà mis à jour avec la structure la plus récente

**Comment by Dominique92** [comment]
Voila. Uploadé.
