### ISSUE TITLE
Protection / user ?

### ISSUE THREAD

**Issue by Dominique92** [RefugesInfo/www.refuges.info#71]
Sur le serveur de prod, les fichiers et répertoires sont en protection 755 / user 1001 (refuges)
Sauf les répertoires qui doivent être accédés en écriture par apache (photo-points) qui sont en protection 755 / user 33 (le user qui fait tourner apache ?)
J'ai eu le pb en uploadant le nouveau forum : git pull me donne des répertoires en 755 / 1001
(je ne sais pas contrôler les protections dans le commit fait depuis windows
Comme je ne peux pas changer le user, j'ai passé les répertoires suivants en 777 :
forum/cache
forum/store
forum/files
forum/images/avatars/upload

Question : qu'est ce qui est le plus logique ?
- avoir une variété de users dans nos répertoires pour assurer l'accès sélectif depuis apache. Mais comment remonter ça dans le GIT ? Et comment documenter l'install
- déprotéger 777 ces répertoires ?

**Comment by sletuffe** [comment]
Désolé, j'avais loupé ce ticket.
Je viens à l'instant de changer toute la logique d'execution de php par apache. Selon moi, et compte tenu de refuges.info c'est le meilleur rapport simplicité/risque

J'utilise à partir de maintenant apache-itk qui permet l'execution de tout script php par l'utilisateur qui possède les fichiers (cas pour sly/www/dom/yip/leo.refuges.info ). Donc le 777 devient inutile, un 755 fait parfaitement l'affaire.

Cette méthode plus pratique présente toutefois un risque légèrement plus élevé en cas de piratage. (pour wri, code unique, je ne m'inquiète pas) mais pour phpBB par contre, un bug autorisant l'accès à certains fichiers pourraient permettre au pirate de ré-écrire le code php.

Mais bon, le risque en vaut la simplicité évoqué selon moi.

La réponse à tes 2 questions devenant : ni l'un ni l'autre.
Pas de multi-user dans git (et pis c'est pas possible en pratique de toute façon) et pas besoin de 777 non plus.
