### ISSUE TITLE
Interface WRI - forum

### ISSUE THREAD

**Issue by Dominique92** [RefugesInfo/www.refuges.info#72]
J'ai rendu compatibles les environnements WRI et PhpBB
- Le gros avantage est que autoconnexion.php gère la connexion aux fiches en appelant la fonction d'autorisation du forum. Donc plus de différences !
note : Il n'y a que 2 niveaux dans WRI aujourd'hui : 0 = rien, >= 1 = tout et le code devient très simple :
https://github.com/RefugesInfo/www.refuges.info/blob/dev-dom/includes/autoconnexion.php#L58-L60
- Il n'y a plus d'appels AJAX intra serveur entre les fiches et le forum.

Conditions nécessaires:
- Suppression de l'autoload WRI dont je n'ai pas trouvé à quoi il servait. Si je n'ai pas vu quelque chose, merci de me le signaler.
- Remplacement de la variable $config de WRI par $wri pour ne pas interférer avec la variable de PhpBB

Autres modifs:
- Les fonctions de modification du forum passent de /forum/ext/RefugesInfo/couplage/api.php dans un nouveau modèle /modeles/forum.php et sont appelées en sous-programme et deviennent très simples
https://github.com/RefugesInfo/www.refuges.info/blob/dev-dom/modeles/point.php#L562-L566
https://github.com/RefugesInfo/www.refuges.info/blob/dev-dom/modeles/point.php#L571-L575
https://github.com/RefugesInfo/www.refuges.info/blob/dev-dom/modeles/point.php#L611
https://github.com/RefugesInfo/www.refuges.info/blob/dev-dom/modeles/forum.php
- Le passage du bandeau et du pied des templates WRI aux templates phpBB devient simple et sans appel externe
https://github.com/RefugesInfo/www.refuges.info/blob/dev-dom/forum/ext/RefugesInfo/couplage/event/listener.php#L61-L76

- On descend d'un cran /includes/config_privee.php qui rejoint la racine parce que :
* ça me fait plaisir :)
* c'est plus facile à trouver pour le modifier
* l'autre fichier à renommer (le modèle .htaccess) est aussi à la racine
* c'est un peu la tradition dans le logiciel forum, ...
* ça préserve l'intégrité du répertoire /includes/... qui contiendra uniquement des fichiers sources
* étant appelé à la fois de WRI (/includes/config.php) et de PhpBB (/forum/config.php), il est logique qu'il soit à la racine
* ça permet de gérer la rupture d'interface ($config -> $wri) lors de l'upgrade puisque l'ancien pourra rester temporairement dans /includes
Enfin, si ça fâche trop, on peut le remettre dans /includes

Pour avis, relecture et tests avant basculement
https://github.com/RefugesInfo/www.refuges.info/tree/dev-dom
http://dom.refuges.info/

**Comment by Dominique92** [comment]
Rappel (pour ceux qui reviennent d'un bivouac en Sibérie)

**Comment by sletuffe** [comment]
va savoir, j'avais en effet loupé ça ;-)

Ben ça m'a l'air plutôt très bien tout ça, je souscris à l'objectif, bien que je n'en discerne pas toutes les nuances ne comprenant pas trop comment marche la machinerie du forum qui fait qu'on se connecte qu'une fois, mais si tu dis que c'est mieux, je te crois !

Juste histoire de faire semblant que je me suis intéressé profondément à tout ça, je vais m'occuper des détails cosmétiques :
$wri : tu as commencé à coder du temps du fortran toi ? à l'époque ou les mémoires se comptait en centaines d'octets et qu'il fallait faire des économies sur le nom des variables ?
Alors bien sûr, maintenant que tu as passé en revu tous les fichiers, ça serait bête de refaire, mais quand même, pour une variable pas explicite, ça se pose là !
Un $conf_wri ou $wri_config m'aurait parru plus explicite, m'enfin.

Pour le config_privee.php à l'a racine, l'arguement "parce que ça me fait plaisir" est tentant, mais je me contenterait de  "étant appelé à la fois de WRI et de PhpBB"
Toutefois, dans cette logique très valable, pourquoi ne pas faire de même pour config.php ?
(ta branche semblant préserver le config.php dans include/ et config_privee.php à la racine)

**Comment by Dominique92** [comment]
Voilà qui est livré.
