### ISSUE TITLE
points de chemineur en https

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#73]
Quand on navigue le site https://www.refuges.info en https
Les points sur la carte (/nav) en provenance de 
pyrenees-refuges.com ©
camptocamp.org ©
chemineur.fr ©

Ne sont pas affichés avec la raison :
Blocage du chargement du contenu mixte actif (mixed active content) « http://chemineur.fr/*******

**Comment by Dominique92** [comment]
En effet. m'avait échappé celui là !
Corrigé. Merci
