### ISSUE TITLE
Faire le deuil da la table points_gps ?

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#74]
Dans l'objectif final d'arriver à ça : https://www.refuges.info/forum/viewtopic.php?f=2&t=5680
(conservation d'un historique avec toutes les modifs des fiches) je pense d'abord passer par la suppression de la table points_gps et de ré-intégration de ses infos à la tables points.

Brin d'histoire, j'avais pour objectif dans un lointain 2008 de factoriser le champs accès+gps+altitude pour des points ayant quasiment la même position : fontaine et sa cabane, partie hiver et son refuge gardé.

L'idée était qu'un repositionnement de l'un repositionne automatiquement celui qui lui ait rattaché, et pis, avec le temps, j'ai jamais codé une interface satisfaisante pour le gérer donc ça n'est utilisé que par ~5 points de la base.
Et dans les faits, on peut souvent positionner, même si c'est 10 mètres, la fontaine au bon endroit par rapport à la cabane.

Bref, c'est plus de problème et de gestion que de gain, je pense donc en finir avec cette table et tout mettre dans une seule "points" quite à duppliquer le texte qui explique comment s'y rendre.

Si pas d'objection/commentaire, ça sera ma prochaine tâche d'ici heu... quand j'aurais le temps

**Comment by Dominique92** [comment]
Entièrement d'accord.

Pour info, dans chemineur, les coordonnées sont dans la table des posts :)
1 point = 1 topic dont le premier post contient le geom de la position (ou de la trace, ...)
Grosse factorisation d'accès.

**Comment by sletuffe** [comment]
https://github.com/RefugesInfo/www.refuges.info/commit/0a1eb844c2e4a16a8e318ea54e402624625ddb1d
