### ISSUE TITLE
dependabot / symphony alert

### ISSUE THREAD

**Issue by Dominique92** [RefugesInfo/www.refuges.info#76]
Github nous alerte gentiment sur une vulnérabilité de la version de symphony, qui est un composant utilisé par phpBB.
Pas d'info sur ça dans les forums phpBB pour l'instant.
J'imagine qu'ils vont réagir par une nouvelle édition mais on ne peut rien faire par nous même.
A suivre donc.

**Comment by sletuffe** [comment]
Vu. Pas de panique, il ne me serait pas venu à l'idée un seul instant de merger leur pull request automatique. Je suis d'ailleurs dubitatif sur la pertinence de leur choix...
Que l'on puisse activer par opt-in ce type d'alertes, admettons, mais qu'elles nous soient "imposées". J'imagine les projets énorme qui dépendent de centaine de classes tierces, ça va leur faire bizarre les dizaines de pull request...
Et j'espère que ceux là ont prévu d'autres outils pour maintenir à jour leurs classes importées (style composer)
Enfin bref, je te laisse choisir mais on peut s'en dé-inscrire, après tout, le forum phpBB étant notre seul dépendance en php, c'est par son système d'upgrade que nous passons.

**Comment by sletuffe** [comment]
laisse nous tranquille github
