### ISSUE TITLE
Fournir un DockerFile pret a l'emploi

### ISSUE THREAD

**Issue by eMerzh** [RefugesInfo/www.refuges.info#79]
Hello, 

Bien que la procédure d'installation semble décrite dans le readme, 
il serait assez utile pour de nouveaux contributeurs de pouvoir lancer le site complet dans un docker, afin de rapidement pouvoir proposer des ameliorations.

**Comment by sletuffe** [comment]
salut,

Disons que si quelqu'un nous propose un "DockerFile" j'ai rien contre d'accepter l'ajout, mais comme je n'utilise pas et ne souhaite pour l'instant pas m'y plonger, je ne m'en occuperais pas.
Ça veut donc dire du suivi car il faudra le maintenir à jour au fûr et à mesure de nos passages à des versions plus récentes de php/postgres/etc

Et notre mode de fonctionnement actuel, si quelqu'un veut nous rejoindre et améliorer le site, c'est plutôt de venir parler sur notre forum, indiquer ce qu'il voudrait ajouter pour en discuter avant de se lancer. Et si je détecte une motivation, je peux sans problème lui créer un espace de développement sur notre serveur, là où il trouvera les mêmes versions qu'en prod, une base déjà pré-rempli avec des données de test et donc, in finé, vu que ça ne va me prendre 10 minutes, un gain de temps pour toute le monde, lui y compris il me semble, vu qu'il n'aura pas à connaître docker ou la gestion technique de tout ce petit monde.

Je ferme ce ticket plus par rangement (j'aime n'avoir que ceux pour lesquels on va vraiment faire quelque chose) mais libre à celui qui veut faire du Docker de le ré-ouvrir et s'en occuper.

**Comment by eMerzh** [comment]
Je comprend que maintenir un truc inutilisé c'est pas évident.
Je songeais a faire quelques ajustements CSS et setuper un linux, apache, php, postgres & postgis pour ça, béh ça refroidis un peu ....
et la solution de développer directement sur le serveur... ça semble pas super optimal non plus....

Bref, ma première contribution sera p-e ce dockerfile ;-)

**Comment by sletuffe** [comment]
> et la solution de développer directement sur le serveur... ça semble pas super optimal non plus....
ha bon ? pourquoi ?
ça ne consiste pas à tester sur le site live, on a des instances indépendantes, le risque de tout planter en changeant le css me semble plus que réduite !

Moi je test sur une instance à cette adresse : https://sly.refuges.info
Je me connecte en sftp ou ssh
j'ai les outils git sur place qui me permet de faire mes push mes pull
C'est un peu moins bien intégré à mon IDE que si les fichiers avaient été en local, mais bon, ça reste acceptable pour moi.

Enfin tout ça pour dire qu'il est possible de créer une instance https://emerzh.refuges.info pour tes tests et que ça prendre bien moins de temps que "setuper un linux, apache, php, postgres & postgis pour ça"
Et tu sera en plus sûr d'avoir toutes les mêmes versions que sur https://www.refuges.info

En autre alternative, www.refuges.info tourne actuellement sur une machine virtuelle utilisant virtualbox, un clone de celle-ci, et un nettoyage des 40Go de photos, des comptes utilisateurs du forum et des comptes locaux est possible aussi.
ça se résume à une suppression des données confidentielles, plutôt qu'une reconstruction de zéro de la base avec les polygones externes (réserves naturelles, massifs, contours de carte topo, départements, ...)
Qui, docker ou pas, va être une assez importante tâche

**Comment by eMerzh** [comment]
Hello, je ne veux pas envenimer le débat ou pousser n'importe quel techno hype, mais mon point était juste que ce serait plus facile d'attirer de nouveaux contributeurs si la procédure pour une installation locale pouvais se résumer git clone ... docker-compose ou autre.

Je ne demande évidemment pas a ce qu'on ME fournisse une db de prod ou n'importe quoi d'autre hein ;-) je suis conscient que c'est un hobby et que chacun fais ce que bon lui semble.

Si je peux me permettre aussi a propos du manuel d'install, j'ai l'impression qu'on alterne les choses complexe avec des trucs assez simple voir élémentaire genre tout un tuto sur git, mais pas une ligne sur le setup de la DB ou du postgis.

**Comment by sletuffe** [comment]
> Hello, je ne veux pas envenimer le débat ou pousser n'importe quel techno hype, mais mon point était juste que ce serait plus facile d'attirer de nouveaux contributeurs si la procédure pour une installation locale pouvais se résumer git clone ... docker-compose ou autre.

Si j'en était sûr, je le ferais ! Mais pour l'instant, je ne suis pas convaincu que ça soit la barrière qui bloque les développeurs qui veulent nous rejoindre. Je pense même que leur fournir un environnement tout prêt tout fait et qui marche (moyennant de savoir déposer des fichiers par sftp et lancer quelques commandes git) et la manière la plus simple de leur permettre de "coder de petites fonctions pour se faire la main"

 
> Je ne demande évidemment pas a ce qu'on ME fournisse une db de prod ou n'importe quoi d'autre hein ;-) je suis conscient que c'est un hobby et que chacun fais ce que bon lui semble.

Pas de soucis, je n'ai pas dis que tu demandais ça, d'ailleurs, si tu veux la structure de notre base, celle sur github ne doit plus être à jour je te fourni un dump sans aucun problème !

> 
> Si je peux me permettre aussi a propos du manuel d'install, j'ai l'impression qu'on alterne les choses complexe avec des trucs assez simple voir élémentaire genre tout un tuto sur git, mais pas une ligne sur le setup de la DB ou du postgis.

En relisant le README.md que j'ai écris, je comprends d'ailleurs pourquoi il y a confusion, je crois l'avoir écrit  initialement comme une note pour moi même (si je devais ré-installer tout) pour finalement me rendre compte que je ne pourrais jamais écrire un "TUTO pour les nuls" avec PG, ça demande des compétences et qui en plus ne sont plus valables 5 ans plus tard que je ne peux pas résumer en 2 pages A4.
J'ai donc abandonné de rentrer dans les détails (installer PG+postGIS, charger les département, les réserves natuelles, les contours de carte IGN, un dump de base à jour) et je constate même que certaines directives ne sont plus d'actualité, ou dépendent d'un environnement particulier.
D'où la deuxième partie du README.md venue plus tard :
"Doc dédiée aux développeurs ayant accès à la machine wri"
qui est plus pertinente (mais toujours pas très à jour)

Je vais essayer de séparer ça en deux :
- Comment faire une INSTALL de wri ailleurs, si on a les compétences PG
- Comment coder sur l'instance que je mets à disposition (donc quelques rappels de l'usage de git, sftp, ssh)

ps: je ré-ouvre, je crois que Dominique voudrait aussi intervenir sur ce thème

**Comment by Dominique92** [comment]
Hello

Je suis le deuxième programmeur du site (il y en a un troisième mais il est en vadrouille dans les terres australes…)

Je suis d’accord avec le besoin de pouvoir installer des instances de refuges.info n’importe où (machine de dev perso, autre hébergeur, …)
Non pour pouvoir créer un autre site de refuges, le code de refuges.info est trop spécifique pour ça.
Si c’est ce que tu cherches, va voir du côté de https://github.com/Dominique92/GeoBB

Le but serait plutôt de pouvoir expérimenter un peu plus au sujet de la programmation
- peut être dans le but de proposer des améliorations (après période probatoire, tu le comprendras)
- peut-être dans le but de réduire la dépendance de notre code à un environnement donné (il faut tout prévoir)

Mon idée est de fournir un paquet de fichiers sous GIT avec quelques incantations ou scripts et un fichier SQL à dérouler n’importe où.
Il faut bien reconnaître qu’on en est loin, tant par la dépendance à PGSQL qu’à la présence d’infos confidentielles dans la base disponible (même la base de tests !)
J’y travaille mais ça ne sera pas pour tout de suite

En attendant, j’abonde dans le sens de la méthode actuelle, proposée par Sylvain, qui est de fournir un environnement de tests perso en état de marche, sur le même serveur.
C’est la méthode que nous avons adopté jusque-là et elle est parfaitement abordable.
Si tu veux te joindre à nous (il serait bon de recruter un peu en effet), ce serait avec le plus grand plaisir mais il faut d’abord qu’on comprenne ce que tu peux nous apporter.
Qui est-tu, d’où viens-tu, quelles sont tes motivations (éventuellement loin d’une collaboration au site), compétences, … ?
Quelles sont tes idées d’évolution du site, tes propositions, techniques ou fonctionnelles, … ?
Tu parles de CSS. Nous sommes assez conservateurs sur le plan de la présentation… à quoi penses-tu ?
Quelle est ton expérience de montagnard ? (on ne réussit pleinement une collaboration à un site qu’en étant soi-même utilisateur ou intéressé par le domaine)…

**Comment by sletuffe** [comment]
> qu’à la présence d’infos confidentielles dans la base disponible (même la base de tests !)
> J’y travaille mais ça ne sera pas pour tout de suite

Pour suivi, si jamais tu veux avancer dans cette voie, j'ai entrepris de nettoyer "ma" base de test de toutes les infos confidentielles de nos membres mais également de la terrible surcharge pondérale qu'impliquait des années de discussion sur le forum, de multiples départements.
J'ai quand même gardé quelques utilisateurs pour les tests, les cabanes pour que ça reste pertinent comme tests. 
Le dump SQL passe à 7Mo en compressé et contient quand même les réserves naturelles, massifs pour pas être sur une coquille vide.
Mon but c'était de pouvoir reloader facilement ma base, mais voilà ça peut servir de "jeu de test"

**Comment by DC92** [comment]
Je vais y travailler (le batch est dans la file)
L'idée n'est pas d'expurger la base actuelle mais de créer une base minimale pour démarrer un site de test. Je compte livrer ça avec un petit englobant des manips d'upgrades de la dernière fois.

**Comment by sletuffe** [comment]
pas de nouvelles, je laisse ré-ouvrir à celui qui arrive avec un projet de docker
