### ISSUE TITLE
Non versionnement des fichiers du forum

### ISSUE THREAD

**Issue by Dominique92** [RefugesInfo/www.refuges.info#80]
Arrive dans 3 ou 4 jours la version 3.2.9 de phpBB (nous sommes en 3.2.8)
Le précédent update m'a montré que ce n'était pas si douloureux que ça et qu'on devrait le faire à chaque release.
Il y a un package automatique pour ça, qui upgrade à la fois la base et les fichiers et qui est très stable.
Le seul problème, c'est qu'il faut upgrader les fichiers du GIT, 1 par 1, sans oublier d'ajouter ceux qu'il faut, modifier ceux qu'il faut et supprimer ceux qui ne sont plus là, avec tout les risques d'en manquer un ! (et franchement, les packages "vendors" aux milliers de fichiers qui changement tout le temps ne sont pas un cadeau !
Et quand on a fait le pull de ça, on ne peut plus utiliser l'outil automatique...

Je propose de déversionner les fichiers venant de phpBB et d'y inclure seulement le .tar qui les contient (avec ou pas un outil automatique pour le détarer si on fait une install)
ça aurait l'avantage de bien séparer les fichiers spécifiques à WRI  (qui sont dans /forum/ext/RefugesInfo/...)

**Comment by sletuffe** [comment]
Est-ce que ça veut dire qu'il va falloir executer le "package" sur chaque instance des développeurs ?
Et si la base (test) est mise en commun, il va refuser de se lancer car la base sera déjà à jour, mais pas les fichiers ?

Pour tout dire, je ne rend pas trop compte, je pensais que :
git add /forum 
+ 
git commit -m "Mise à jour du forum"
suffisait pour les fichiers.
Et que le "problème" c'était l'upgrade de la base.

Mais comme très gros avantage, je voyais moi que, n'y connaissant pas assez de l'upgrade phpBB, la dernière fois, je t'ai laissé oeuvrer, et un simple "git pull" comme d'habitude à tout géré sur mon instance.

Après, je n'ai rien contre d'essayer, la 3.2.9 qui arrive nous permettra de nous rendre compte sans qu'il y ait de risque pour la prod.
Puisque, si j'ai bien compris, tu vas executer le "package" sur www.r.i et au pire, c'est sur nos instances de développement que ça peut avoir des problèmes.
Je dis ok !

**Comment by sletuffe** [comment]
on peut fermer, tout roule avec la nouvelle procédure
