### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable 

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#81]
Sur la page https://sly.refuges.info/point/3605/cabane-non-gardee/Le-Grillet/
si on active l'affichage des erreurs, on obtient, vers le bas le message :
 **Warning: count(): Parameter must be an array or an object that implements Countable in /home/users/sly/www.refuges.info/vues/point.html on line 255**

Ce problème est apparu au passage à php 7.3 car n'était pas considéré avant comme une erreur par php.

Celui-ci n'est pas simple à corriger et se trouve un peu partout dans le code et il y a plusieurs méthodes pour corriger.

Le "problème" initial c'est que j'ai utilisé la syntaxe des objet sour la forme 
`$vue->propriete="coucou"; `
alors que $vue (dans ce cas) n'a jamais eu de méthodes.
Si j'avais utilisé la syntaxe 
`$vue['propriete']="coucou"; `
le problème de se serait pas manifesté, car les array sont "countable" par défaut.

Mais j'avais comme espoir, ou envisagé, un jour, d'ajouter des méthodes à l'objet vue pour par exemple générer une vue en fonction d'un template plutôt que bidouiller avec des include et, pourquoi pas, créer un petit moteur de cache.

enfin bref, ça aurait été plus simple de migrer vers l'object avec déjà la syntaxe ->
sauf que voilà, un objet n'est plus countable par défaut.

Soit je passe vraiment à de l'objet "version light" et la seule méthode que j'écris pour l'instant c'est celle qui compte les propriétés (foreach ($self as bidule))
Solution longue mais tournée vers l'avenir !

Soit je converti mon object en array, il perd les méthodes qu'il n'a pas et il devient countable automatiquement
`if (count ( ($vue)==1 ))`

j'y réfléchi, avis bienvenus !

**Comment by Dominique92** [comment]
Salut

J’ai depuis longtemps été dubitatif quant à la définition d’objets de classe générique stdClass pour y mettre des données dedans
Pour moi, ce n’est pas un objet (qui instancie une classe qui a une raison d’être et des méthodes), ce devrait être un array.
Peut-être pour la beauté du -> ?
Quant à savoir pourquoi on veut compter un objet ??? tu vois bien que c’est un tableau :)

Dom

**Comment by sletuffe** [comment]
reprenant ce bug que j'essaye de corriger, je constate que mon analyse du problème était complètement fausse, aucune des ~8 erreurs de ce type que j'ai pour l'instant rencontré n'était dû au fait que le count voulait compter les propriétés d'un objet.
J'ignore complètement comment j'en suis arrivé à cette idée.

Bref, après vérif, le count était bien à chaque fois appliqué à un array, à chaque fois dans le but de savoir s'il y avait ou non des éléments dans l'array pour lancer un traitement.
Si cette erreur sortait, c'est en fait bien lié à un changement de php 7.0 à 7.3 couplé au fait que nos array n'était jamais initialisées.

En code simplifié, la méthode utilisée était la suivante :
```
foreach ($machins as $machin)
{
if (on veut celui là)
  array_des_machins[]=$machin;
}

if count($array_des_machins) ...
```

Et bien quand aucun machin n'avait été choisi, l'array n'était pas uniquement vide mais non définie comme array. Et count rallait qu'on tentait de compter un truc non défini. Là ou avant il était d'accord pour dire que ça vallait 0

Un 
`$array_des_machins = array();`

semble régler le problème

**Comment by sletuffe** [comment]
j'en ai corrigé plusieurs, je les ferais au fûr et à mesure, de toute façon, sur le www l'erreur n'est pas affichée donc y'a point de drame
