### ISSUE TITLE
url www.refuges.info en dur dans le code OL

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#82]
Sur cette ligne :
https://github.com/RefugesInfo/www.refuges.info/blob/master/MyOl/myol.js#L862

" www.refuges.info" est écrit en dur. Ce qui fait que j'ai plus de mal à débugger l'API sur mon instance sly.refuges.info vu que ça appel l'api de wri.

J'imagine que l'objectif est une diffusion plus large du code de carte, mais y'aurait il une solution qui m'évite de modifier la ligne sur mon instance ? (écrasement au prochain "git pull")

**Comment by Dominique92** [comment]
Bha non : cette ligne (idem sur index.js / point_modification.js / edit.js
https://github.com/RefugesInfo/www.refuges.info/blob/master/vues/nav.js#L46
écrase le paramètre qui est dans le logiciel commun et va bien chercher les couches dans ton instance.
Tu as un traffic sur WRI dans ton browser ? (j'en ai peut-être oublié un )

**Comment by sletuffe** [comment]
Oui, il me reste du trafic vers wri quand je suis sur mon instance, mais j'ai mal regardé, l'api est bien appelée sur mon instance, ce sont les icônes qui sont récupérées sur wri (je n'ai pas fais attention dans la liste des appels)

Comme je venais de changer mes icônes pour un test je m'étonnais que la légende le prenne en compte mais pas la carte.

**Comment by Dominique92** [comment]
Pas plus : je reprends bien la baseurl
https://github.com/RefugesInfo/www.refuges.info/blob/master/MyOl/myol.js#L880

Par contre, sur ton instance, il y a une trace d'erreur dans ton flux JSON parce que tes clés de cartes ne sont pas dans ton conf_privee, ce qui masque l'affichage des icones
J'ai fait un patch pour ne pas qu'il génère d'image

**Comment by sletuffe** [comment]
J'ai fais l'erreur de faire un "git pull" au mauvais moment on dirait ;-) 
ça m'a rammené tous tes patchs qui semble comme tu l'as dis parlé de clé que je n'ai peut-être pas.

Bon, pour les besoins de la démonstration, je reviens en arrière :
https://sly.refuges.info/nav?map=13/5.74498/45.30469

On voit comme la légendre à gauche ne charge pas les mêmes icones que sur la carte

**Comment by Dominique92** [comment]
Yes ! Il manquait un baseUrl.
Comme les premières icônes (de la légende) semblaient venir du bon serveur, je n'ai pas vu qu'il y en avait d'autres (dans la carte) du mauvais.
Bien vu !

**Comment by sletuffe** [comment]
Donc, pour le bug référencé en objet, j'ai mis à jour mon instance et tout roule nikel maintenant, donc bug corrigé : merci.

Pour les erreurs (json ?) :

> Par contre, sur ton instance, il y a une trace d'erreur dans ton flux JSON parce que tes clés de cartes ne sont pas dans ton conf_privee, ce qui masque l'affichage des icones
> J'ai fait un patch pour ne pas qu'il génère d'image

Alors pour ça, je ne suis pas sûr d'avoir tout suivi, tout à l'heure lors de mon git pull, j'ai constaté 3 erreurs du genre "php blabla ign_key, index not found" "Ordonance Survey, idem" et j'ai oublié la 3ème erreur.

Depuis, je suis revenu en arrière, puis j'ai refais une mise à jour à la dernière version de master, et les erreurs sont parties, les cartes IGN fonctionnent et je ne note rien de spécial. Bref, soit c'est tombé en marche, soit tu as fais quelque chose entre temps qui "ignore" les clés que je n'ai pas ?

Dans mon conf privé j'ai ça : 
$config_wri['ign_key']='5l..............................';
$config_wri['bing_key']='Ar....................................'; // https://www.bingmapsportal.com
$config_wri['os_key']='C...................................'; // http://www.ordnancesurvey.co.uk/business-and-government/products/os-openspace/

les 2 premiers marchent, le 3 ème je ne sais pas, je ne l'ai pas dans le menu

**Comment by Dominique92** [comment]
Alors je n'ai pas compris pourquoi tu avais ces 3 erreurs que j'ai vu aussi
Entre temps, j'ai fait en sorte que le manque de clés ne génère pas d'erreur (il n'affiche pas la couche correspondante, c'est tout)

Tu devrais avoir les 3 clés de la conf_modéle (vois dans WRI pour les valeurs)
os_key esy obsolète (c'était les cartes anglaises passées maintenant chez Bing / Microsoft)
Il te manque thunderforest_key qui donne la couche Outdoors
