### ISSUE TITLE
Sur la carte, les points d'eau en provenance d'overpass ramènent tous les noeuds de la zone

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#84]
Si je vais là : https://www.refuges.info/nav/11/massif/Beaufortain/
je coche "Services ([ OSM ](https://overpass-turbo.eu/)) - disponible seulement pour les zoom forts
=>    point d'eau

J'ai un machin de 18Mo qui m'est retourné avec une nuée de point qui sort de la demande des uniques points d'eau

**Comment by Dominique92** [comment]
ha ben ! qu'est-ce qui m'a pris d'optimiser une ligne html en la coupant avec des '+' comme en  javascript :) :) :)
