### ISSUE TITLE
formulaire_rss : idzone 'null' sur case à cocher 

### ISSUE THREAD

**Issue by Binnette** [RefugesInfo/www.refuges.info#85]
Bonjour, un bug c'est glissé dans la page http://www.refuges.info/formulaire_rss

Il semblerait que la dernière "zone" en bas de page n'est pas d'id_zone (ou ne soit pas du tout une zone).

Du coup, les cases "tout cocher" et "tout décocher" ne fonctionne pas.

[![2022-11-14-10-04-50-Flux-RSS-des-nouvelles-du-site-Refuges-info-Mozilla-Firefox.png](https://i.postimg.cc/G27bJvbK/2022-11-14-10-04-50-Flux-RSS-des-nouvelles-du-site-Refuges-info-Mozilla-Firefox.png)](https://postimg.cc/HcMGTcc8)

Merci d'avance pour la correction. Et merci aussi pour cet excellent "site web"/plateforme/communauté !!!! Bonne journée.

**Comment by sletuffe** [comment]
Merci pour ce retour précis !
En effet, je ne sais pas depuis quand ça ne marche plus mais vu qu'on y a pas touché depuis des lustres, c'est dire si les gens s'en servent ;-)
Bon, en effet, ce sont les massifs qui ne sont dans aucune "grande zone" et qui de se fait retourne un identifiant <vide> que le js n'accepte pas de cocher. Voilà qui est corrigé.

**Comment by sletuffe** [comment]
Le lien d'info est en bas à droite du lien que tu cites. Mais pas très visible, j'en conviens, je viens d'améliorer pour plus de clarté.
C'est par là : https://wiki.openstreetmap.org/wiki/Hiking/mri
