### ISSUE TITLE
Identification hors du forum

### ISSUE THREAD

**Issue by Dominique92** [RefugesInfo/www.refuges.info#86]
Je suis dépité. Je pense que j'ai été dans la mauvaise direction.

On n'y arrivera jamais. Il y a à chaque fois un cas particulier qui fait tout foirer.
Et cette fois, je ne trouve pas.
Le forum tient compte de plein d'autres paramètres pour accorder la connexion (IP, infos navigateur, ...)
Le code de phpBB est illisible et basé sur l'identification de Symphony + quelques addons triturés à souhait pour perdre le plus chevronné des hackers.
Et on n'est pas à l'abri d'un changement intempestif à l'occasion d'un correctif de sécurité

La première option était la bonne : charger le forum au début de chaque page pour bénéficier de l'authentification.
Ça me faisait très C*** parce que ça fait tourner le serveur (et SQL) pour peut-être pas grand chose, alors j'ai essayé de contourner...

Mais je viens de découvrir que modeles/forum charge aussi le forum
et, comme ils appelé par  modeles/commentaire, controlleurs\gestion\moderation, controlleurs\nav, controlleurs\point_modification ... qui sont appelés aux même par controlleurs\gestion\moderation, commentaire, controlleurs\nouvelles, controlleurs\point_ajout_commentaire, commentaire.php, ...
Bon, en fait, toutes les mages chargent le forum...
Même la page d'accueil puisqu'elle affiche les news qui appellent...
Rien d'anormal à ça mais il faut constater que le forum est chargé de toute façon

Certes, modeles/forum n'est utilisé qu'en cas d'écriture de point ou de commentaire mais, comme les modèles ne sont pas divisés en fonctions lectures / écriture, on charge tout le temps :(
Bon, on ne va pas refaire l'architecture MVC pour ça !

Je pense que je vais revenir au modèle "on demande toujours au forum de calculer les autorisations"
Je me donne 1 ou 2 jours pour penser calmement et avoir d'autres avis.
Ça laisse un peu de temps pour se redemander où mettre les fonctions communes à toutes les pages.
Quitte à refaire un peu d'archi et une bonne phase de tests après, autant y incorporer 2 ou 3 ménages

Une idée serait de placer les fonctions modeles/identification dans modeles/forum de façon à n'avoir qu'un point d'inclusion des fichiers phpBB. A bien réfléchir, l'identification est une fonction du forum

**Comment by Dominique92** [comment]
Je pose la question et j'y répond.
L'overhead de charger le contexte forum est de 37 ms.
Probablement pas plus que tous les accès DB qui étaient maintenant dans l'identification.
Pour finir, le code est ultra simple et le même sur une page forum et site

**Comment by sletuffe** [comment]
Ok pour moi.
Je n'ai plus souvenir des détails, mais si on avait choisi de se passer du chargement forum, c'est qu'a un moment, peut-être, on devait être bien au delà des 37ms sinon en effet le jeu n'en vaut pas la chandelle.
Peut-être que des améliorations coté système ont entre temps réduit le temps de chargement de grosses classes ?

Et si on peut garder l'API qui est parfois demandée plusieurs fois sans le chargement forum dont elle n'a de toute façon pas besoin (je crois) alors tant mieux pour la réactivité.
