### ISSUE TITLE
Bandeau de login en haut à droite bizarrement fonctionnel sur Firefox

### ISSUE THREAD

**Issue by sletuffe** [RefugesInfo/www.refuges.info#90]
hello,

Pas certain que ça soit d'une importance capitale, surtout si ça ne touche que moi, mais le bandeau de login en haut à droite se comporte bizarrement sous FF, et une vidéo valant mieux qu'un long discours
[Sans titre.webm](https://github.com/RefugesInfo/www.refuges.info/assets/732006/43234129-003f-4898-b6cd-f709376e52d6)

**Comment by Dominique92** [comment]
Pour être honnête, je l'avais vu depuis des années mais je n'avais jamais été jusqu'à soulever ma flemme pour investiguer.
En fait, ça fonctionnait très bien en cliquant sur "Connexion" plutôt que de survoler... mais il n'y a pas de raisons de ne pas le corriger.

**Comment by sletuffe** [comment]
You make it look easy !

**Comment by Dominique92** [comment]
> You make it look easy !

Sauf que ça marche plus sur mobile... A refaire

**Comment by sletuffe** [comment]
ha bon ? FF Mobile et FF desktop : tout marche.
Ou alors je suis déjà sur la version corrigée ;-)

**Comment by sletuffe** [comment]
Je fais le ménage, j'ai testé ce bug avec FF Mobile et chrome et il n'existe plus, tout roule.
